server:
  port: 2222
spring:
  application:
    name: 03-Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rushikesh052/configuration-properties.git
          clone-on-start: true
